
# Java context path
server.servlet.context-path: /java

# URL to node app
app.node.url: ${NODE_APP_URL}

spring:
  jpa:
    properties.hibernate:
      temp.use_jdbc_metadata_defaults: false

  datasource:
    url: ${DB_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
